version: '3.3'

services:
  lab3_db:
    container_name: lab3_db
    image: percona:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
    ports:
      - 3306:3306
    volumes:
      - lab3_db_volume:/var/lib/mysql
      - .:/data/.:ro
    cap_add: [ SYS_NICE ]

volumes:
  lab3_db_volume: