up:
	docker-compose up -d

down:
	docker-compose down

task14_up:
	docker exec -it lab3_db sh -c 'mysql -uroot -ppass1234 < /data/task14/up.sql'

task14_down:
	docker exec -it lab3_db sh -c 'mysql -uroot -ppass1234 < /data/task14/down.sql'

task15_up:
	docker exec -it lab3_db sh -c 'mysql -uroot -ppass1234 < /data/task15/up.sql'

task15_down:
	docker exec -it lab3_db sh -c 'mysql -uroot -ppass1234 < /data/task15/down.sql'
