DROP TABLE IF EXISTS `evidence`;
DROP TABLE IF EXISTS `criminal_to_case`;
DROP TABLE IF EXISTS `case`;
DROP TABLE IF EXISTS `imprisonment`;
DROP TABLE IF EXISTS `criminal`;
DROP TABLE IF EXISTS `prisoner`;

DROP DATABASE IF EXISTS `task14`;
